name: edutrack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^0.13.6 
  shared_preferences: ^2.2.2
  file_picker: ^10.2.0
  sqflite: ^2.3.2
  path_provider: ^2.1.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.2
  path: ^1.9.0
  image_picker: ^1.1.0
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
